ALTER TABLE "Country" ADD COLUMN "alpha3" TEXT;

UPDATE "Country"
SET "alpha3" = CASE "iso2"
  WHEN 'US' THEN 'USA'
  WHEN 'GB' THEN 'GBR'
  WHEN 'CA' THEN 'CAN'
  WHEN 'CN' THEN 'CHN'
  WHEN 'HR' THEN 'HRV'
  WHEN 'NL' THEN 'NLD'
  WHEN 'EG' THEN 'EGY'
  WHEN 'PH' THEN 'PHL'
  WHEN 'FR' THEN 'FRA'
  WHEN 'GR' THEN 'GRC'
  WHEN 'IN' THEN 'IND'
  WHEN 'IE' THEN 'IRL'
  WHEN 'IT' THEN 'ITA'
  WHEN 'JM' THEN 'JAM'
  WHEN 'JP' THEN 'JPN'
  WHEN 'KE' THEN 'KEN'
  WHEN 'MY' THEN 'MYS'
  WHEN 'MX' THEN 'MEX'
  WHEN 'MA' THEN 'MAR'
  WHEN 'PL' THEN 'POL'
  WHEN 'PT' THEN 'PRT'
  WHEN 'RU' THEN 'RUS'
  WHEN 'ES' THEN 'ESP'
  WHEN 'TH' THEN 'THA'
  WHEN 'TN' THEN 'TUN'
  WHEN 'TR' THEN 'TUR'
  WHEN 'UA' THEN 'UKR'
  WHEN 'UY' THEN 'URY'
  WHEN 'VN' THEN 'VNM'
END;

ALTER TABLE "Country" ALTER COLUMN "alpha3" SET NOT NULL;

CREATE UNIQUE INDEX "Country_alpha3_key" ON "Country"("alpha3");
